### ISSUE TITLE
Casos de Uso

### ISSUE THREAD

**Issue by afar-cmyk** [lufermaxi/ProyectoBibliotech#10]
Desarrollar los casos de uso conforme a lo establecido en las historias de usuario.

- [x] Descripciones.

**Comment by jsstiven** [comment]
casos de uso terminados faltan los diagramas de caso de uso que lo va a realizar el compañero esteban

**Comment by afar-cmyk** [comment]
> casos de uso terminados faltan los diagramas de caso de uso que lo va a realizar el compañero esteban

Por favor, comunicale al compañero que apenas termine de desarrollar los diagramas, venga a este issue, marque en la lista de chequeo los diagramas como terminados y que cierre el issue con un comentario . Gracias.

**Comment by afar-cmyk** [comment]
El documento de descripciones de los casos de uso ya fue revisado por el tutor en el Sprint 0, solo falta realizar los diagramas #15 .
