### ISSUE TITLE
Ajuste de Mockups (2)

### ISSUE THREAD

**Issue by afar-cmyk** [lufermaxi/ProyectoBibliotech#11]
Conforme a la reunión del día de hoy se deben realizar las siguientes tareas:

1. Ajustar los _mockups_ con los nuevos requerimientos:
    - [x] Kelly
    - [x] Andrés

2. Subir los _mockups_ en formato PDF:
    - [x] Kelly
    - [x] Andrés

3. Unir los _mockups_ de Usuario y Administración:
    - [x] PDF de _mockups_ subido a Google Drive.

**Comment by muakarada** [comment]
De acuerdo a la reunión se ajustan las categorías (aquí formatos) para fijar la búsqueda del cliente, se actualiza el archivo PDF para unificar con dashboard de usuarios.

**Comment by afar-cmyk** [comment]
Conforme a lo establecido en la reunión de hoy se ha realizado estos cambios en los **_mockups_**:

- Portal Administrativo
Usuario Root:
1. Se ha cambiado el _input_ de _tags_ en las paginas de creación y edición de artículos por una lista desplegable con las nuevas categorías.
2. Se han cambiado los criterios de los filtros para que sean igual a las nuevas categorías.

Se han unido los _mockups_ del **portal cliente** con el **portal administrativo** en una nueva presentación de PDF y se ha subido a la carpeta compartida de Google Drive.
