### ISSUE TITLE
Casos de Uso (Diagramas)

### ISSUE THREAD

**Issue by afar-cmyk** [lufermaxi/ProyectoBibliotech#15]
Desarrollar los **diagramas de casos de uso** conforme a lo establecido en las historias de usuario y las descripciones ya realizadas en el **Sprint 0**.

- [x] Diagramas con los actores y los casos.

**Comment by Jesteban247** [comment]
[Caso de usoMINTIC.docx](https://github.com/lufermaxi/ProyectoBibliotech/files/7165940/Caso.de.usoMINTIC.docx)

Realizado según indicaciones

**Comment by afar-cmyk** [comment]
> [Caso de usoMINTIC.docx](https://github.com/lufermaxi/ProyectoBibliotech/files/7165940/Caso.de.usoMINTIC.docx)
> 
> Realizado según indicaciones

Hola compañero, para esta _Issue_ solo era necesario subir el archivo a Google Drive y marcar en el _checkbox_ que se habia llevado a cabo la tarea, para luego cerrar la _issue_ con un comentario, de todos modos se revisara en la carpeta compartida.

![image](https://user-images.githubusercontent.com/83623263/133363732-8333a9e4-418d-4434-a687-bb81e8d0077c.png)

**Comment by afar-cmyk** [comment]
Hace falta revisión por parte del tutor, se cierra la _issue_.
