### ISSUE TITLE
Estructura de carpetas: desarrollo web

### ISSUE THREAD

**Issue by muakarada** [lufermaxi/ProyectoBibliotech#16]
Actividades

- [x] Crear el commit con la estructura de carpetas para inicio de trabajo en desarrollo web

**Comment by muakarada** [comment]
Actividades

Leyendo la documentación creo que para trabajar todos nos tocaría crear ramas independientes, pero quedo a la espera de sus comentarios.

**Comment by afar-cmyk** [comment]
> Actividades
> 
> Leyendo la documentación creo que para trabajar todos nos tocaría crear ramas independientes, pero quedo a la espera de sus comentarios.

Tienes razón compañera, sin embargo, para comenzar a trabajar en el proyecto necesitabamos una estructura base, con el fin de que a la hora de ramificar el repositorio las nuevas adiciones de archivos no quedaran desordenadas y en lugares que no se deseaban.

Supongo que con este nuevo _commit_ podemos poner en marcha la creación de las paginas que van a conformar el sitio.

**Comment by afar-cmyk** [comment]
Supongo que ninguno tendremos problemas de duplicados (bueno, eso espero... 😶), cierro el Issue.
