### ISSUE TITLE
GitHub project (Scrumboard - tareas)

### ISSUE THREAD

**Issue by lufermaxi** [lufermaxi/ProyectoBibliotech#2]
* Se configura el board disponible en Git Hub.
* Se definen las tareas dentro del board.

**Comment by lufermaxi** [comment]
Se explico al equipo el funcionamiento del tablero, creación y gestión de tareas.

**Comment by afar-cmyk** [comment]
> Se explicó al equipo de desarrollo el funcionamiento del tablero, creación y gestión de tareas.

Buenisimo, si ya se terminó este issue es mejor cerrarlo y pasarlo a Done.
