### ISSUE TITLE
Navegacion entre interfaces

### ISSUE THREAD

**Issue by afar-cmyk** [lufermaxi/ProyectoBibliotech#22]
Asegurar la navegación entre las siguientes paginas:

- [x] #19 
- [x] #20 
- [x] #21 
- [x]  #29
- [x] #28 

Importante!! basarse en la [jerarquía del sitio y los nombres de archivo](https://docs.google.com/presentation/d/1ETA3zJ_fJ5ClMBFnPRGFU_XgEP62md20XkgyAmkx1Zg/edit?usp=sharing) que han sido previamente establecidos.

**Comment by jsstiven** [comment]
realice la navegacion entre las paginas requeridas para el sprint 1 y 2
