### ISSUE TITLE
Historias de usuario (Sprint 2)

### ISSUE THREAD

**Issue by afar-cmyk** [lufermaxi/ProyectoBibliotech#26]
- [x] Desarrollar las historias de usuario para el Sprint 2.

[Fuente](https://github.com/luisguillermomolero/MisionTIC2022/blob/main/Modulo3_Web_MisionTIC2022_Main/Semana_1/13_Sprints_Proyecto.pdf)

**Comment by jsstiven** [comment]
las nuevas historias de usuarios son las que tienen los ID 13, 15, 16, 12 y11
Las historias de usuario modificadas son los de ID 14,10, 9 y 5
