### ISSUE TITLE
Creación repositorio - colaboradores

### ISSUE THREAD

**Issue by lufermaxi** [lufermaxi/ProyectoBibliotech#3]
# Repositorio

Se gestionará el proyecto a través del tablero Github Projects, donde los sprint estarán identificados con hitos (Milestones) y ciertas etiquetas (Labels) informarán sobre características de cada tarea.

### Los colaboradores en BIBLIOTECH son:
* Álvarez Felipe
* Esteban Castiblanco
* Delgado Fernando
* Monroy Kelly
* Vásquez John

**Comment by afar-cmyk** [comment]
Si este issue ya se desarrolló es mejor cerrarlo.
