### ISSUE TITLE
Creación historias de usuario.

### ISSUE THREAD

**Issue by lufermaxi** [lufermaxi/ProyectoBibliotech#6]
Las historias de usuario se desarrollan en el documento HISTORIAS DE USUARIO.docx que se encuentra en el drive.

**Comment by jsstiven** [comment]
historias de usuarios del sprint 0 terminadas faltan las planeadas para el sprint 1 y 2 junto con la de formato hablada en la reunion con la fecha 13/09/2021 a las 5:00 pm
