### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by lufermaxi** [lufermaxi/ProyectoBibliotech#7]
# Wireframes  y Mockups

Se usará la herramienta online FIGMA en este proceso.

**Comment by muakarada** [comment]
Mockups: primera presentación del diseño de los mockups de la página web de Bibliotech (inicio y acceso cliente), anotaciones del instructor:

- Revisión de los criterios de búsqueda de los artículos
- Modificar con banners los artículos que no estarían disponibles para facilidad del usuario
- Añadir a los mockups las páginas restantes: Header, servicios, noticias, equipo, footer (según implementación del proyecto)
- Mockup total de la página web completa con las secciones propuestas 
- Mockup responsive para smartphones y tablets

**Comment by afar-cmyk** [comment]
Se desarrollaron los _mockups_ conforme a las interacciones que fueron planteadas en las historias de usuario que hay hasta la fecha.
