### ISSUE TITLE
Ajustes de Mockups

### ISSUE THREAD

**Issue by afar-cmyk** [lufermaxi/ProyectoBibliotech#8]
Realizar ajustes a los _mockups_ conforme a las recomendaciones dadas por el tutor.

- [x] Kelly
- [x] Andrés

**Comment by muakarada** [comment]
Ajustes de los mockups de la página web según especificaciones del tutor, tareas por completar:

- Aprobación del grupo de trabajo
- Ajustes en las búsquedas de artículos de los clientes
- Diseño responsive (Smartphones y tablets)

**Comment by afar-cmyk** [comment]
Ajustes en los _mockups_ conforme a las opiniones del del tutor:

**General**:
- Se reorganizó la posición de los _mockups_.
- Se separaron los _mockups_, ahora estan agrupados por Rol.

**Usuario _Root_**:
- Se modificó el _label_ de identificación de rol en el menú lateral con un color de relleno.

**Usuario Administrador**:
- Se modificó el _label_ de identificación de rol en el menú lateral con un color de relleno.
- Se removió el botón de "Administradores" en el menú lateral.
- Se removió el modulo de "Administradores Recientes" de la pagina "Recientes".
- Se removieron las paginas y las características de creación y edición de **Artículos**.

**Comment by afar-cmyk** [comment]
Conforme a la reunión del día de hoy llevar se deben realizar las siguientes tareas:

1. Ajustar los _mockups_ con los nuevos requerimientos:
    - [ ] Kelly
    - [ ] Andrés

2. Subir los mockups en formato PDF:
    - [ ] Kelly
    - [ ] Andrés

3. Unir los mockups de Usuario y Administración:
    - [ ] PDF de mockups subidos a Google Drive
